python3 -m pip install cffi==1.11.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install chardet==3.0.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install click==6.6 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install colorama==0.3.7 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install constantly==15.1.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install coremltools==2.1.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install crcmod==1.7 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install cryptography==2.1.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install cssselect==1.0.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install cvxopt==1.2.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install cycler==0.10.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install dateparser==0.7.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install decorator==4.1.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install deepctr==0.3.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install defusedxml==0.5.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install docopt==0.6.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install docutils==0.14 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install dotmap==1.2.20 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install elasticsearch==6.1.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install elasticsearch-async==5.2.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install entrypoints==0.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install enum34==1.1.6 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install et-xmlfile==1.0.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Fabric3==1.14.post1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install feedfinder2==0.0.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install feedparser==5.2.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install ffmpeg==1.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install ffmpeg-normalize==1.3.8 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask==1.0.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-Admin==1.5.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-BabelEx==0.9.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-Cors==3.0.6 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install flask-jsondash==6.2.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-Login==0.4.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-Mail==0.9.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-Principal==0.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-RESTful==0.2.5 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-Script==2.0.6 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-Security==3.0.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-SQLAlchemy==2.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-Uploads==0.2.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Flask-WTF==0.14.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install future==0.17.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install gast==0.2.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install gensim==3.7.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install graphviz==0.8.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install grpcio==1.18.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install h5py==2.9.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install hiredis==0.2.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install hjson==3.0.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install html5lib==0.9999999 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install HTMLParser==0.0.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install hurry.filesize==0.9 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install hyperlink==17.3.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install hypothesis==3.88.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install idataapi-transform==1.0.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install idna==2.8 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install incremental==17.5.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install ipykernel==5.1.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install ipython==6.1.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install ipython-genutils==0.2.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install ipywidgets==7.4.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install itchat==1.2.32 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install itsdangerous==0.24 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install jdcal==1.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install jedi==0.13.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install jieba==0.39 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install jieba3k==0.35.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Jinja2==2.10 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install jmespath==0.9.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install joblib==0.13.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install jsonschema==2.6.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install jupyter==1.0.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install jupyter-client==5.2.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install jupyter-console==6.0.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install jupyter-core==4.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Keras==2.2.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Keras-Applications==1.0.7 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Keras-Preprocessing==1.0.9 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install kombu==4.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install langdetect==1.0.7 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install llvmlite==0.28.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install logzero==1.5.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install lxml==3.8.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Markdown==2.6.11 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install MarkupSafe==1.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install matplotlib==2.0.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install mistune==0.8.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install mock==2.0.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install more-itertools==6.0.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install multidict==4.0.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install mxnet==1.1.0.post0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install nbconvert==5.4.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install nbformat==4.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install networkx==2.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install newspaper3k==0.2.5 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install nltk==3.2.5 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install notebook==5.7.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install numba==0.43.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install numpy==1.16.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install olefile==0.44 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install onnx==1.3.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install opencv-python==3.4.0.12 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install openpyxl==2.4.10 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install oss2==2.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pandas==0.24.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pandocfilters==1.4.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install paramiko==2.4.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install parsel==1.2.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install parso==0.3.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install passlib==1.7.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pbr==5.1.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install peewee==3.9.5 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pexpect==4.3.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pickleshare==0.7.5 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Pillow==4.2.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pipreqs==0.4.9 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pkuseg==0.0.21 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install plac==0.9.6 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pluggy==0.9.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install prettytable==0.7.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install prometheus-client==0.5.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install prompt-toolkit==2.0.9 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install protobuf==3.6.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install psutil==5.4.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install ptyprocess==0.5.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install py==1.8.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install py4j==0.10.7 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pyasn1==0.4.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pyasn1-modules==0.2.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pycandela==0.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pycparser==2.18 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pycurl==7.43.0.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pyDes==2.0.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install PyDispatcher==2.0.5 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install PyExecJS==1.5.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Pygments==2.3.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pymongo==3.3.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Pympler==0.5 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install PyMySQL==0.7.11 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install PyNaCl==1.2.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pyodps==0.8.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pyOpenSSL==17.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pyparsing==2.2.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install PyPDF2==1.26.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pypng==0.0.19 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install PyQRCode==1.2.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pyquery==1.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pyspark==2.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pytesseract==0.2.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pytext-nlp==0.1.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install python-dateutil==2.8.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install python-docx==0.8.10 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install python-dotenv==0.10.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pytz==2018.9 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install PyYAML==3.12 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install pyzmq==17.1.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install qcloudapi-sdk-python==2.0.8 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install qtconsole==4.4.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install queuelib==1.4.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install radar==0.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install readability-lxml==0.6.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install redis==2.10.6 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install regex==2019.4.14 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install requests==2.21.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install requests-file==1.4.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install requests-mock==1.5.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install resampy==0.2.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install rsa==3.4.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install s3transfer==0.1.11 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install scikit-learn==0.20.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install scikit-surprise==1.0.6 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install scipy==1.2.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Scrapy==1.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install selenium==3.141.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Send2Trash==1.5.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install service-identity==17.0.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install simplegeneric==0.8.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install six==1.11.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install sklearn==0.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install smart-open==1.8.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install speaklater==1.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install SQLAlchemy==1.2.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install stevedore==1.30.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install tensorboard==1.13.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install tensorboardX==1.6 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install tensorflow==1.13.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install tensorflow-estimator==1.13.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install tensorflow-tensorboard==0.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install termcolor==1.1.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install terminado==0.8.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install testpath==0.4.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install threadpool==1.3.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install tldextract==2.2.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install torch==1.0.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install torchtext==0.3.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install torchvision==0.2.2.post3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install tornado==4.5.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install tqdm==4.30.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install traitlets==4.3.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install turicreate==5.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Twisted==17.9.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install typing==3.6.6 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install typing-extensions==3.7.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install tzlocal==1.5.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install urllib3==1.24.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install uvloop==0.9.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install uWSGI==2.0.18 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install vine==1.2.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install virtualenv==16.4.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install virtualenv-clone==0.5.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install virtualenvwrapper==4.8.4 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install w3lib==1.18.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install warcio==1.5.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install wcwidth==0.1.7 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install Werkzeug==0.14.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install wget==3.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install widgetsnbextension==3.4.2 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install wordcloud==1.5.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install WTForms==2.2.1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install wxpy==0.3.9.8 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install xlearn==0.40a1 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install xlrd==1.1.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install xlwt==1.3.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install yarg==0.1.9 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install yarl==1.1.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install zhconv==1.4.0 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
python3 -m pip install zope.interface==4.4.3 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com